id: PBD7D4656
initial_creation_type: input
source_metadata:
  title: Lhatsün Namkha Jigme Series
  language: bo
  description: 'Texts associated with the famous yogi Lhatsün Namkha Jigme (lha btsun
    nam mkha'' ''jigs med, 1597–1650), who is credited with ''opening the hidden land''
    of Sikkim:'
  volume:
    f99adf303d37402fba1215bebdda2794:
      title: The Gentle Rain of Benefit and Joy - An Explanation of the Practice of
        Sang Offering
      parent: Commentaries
    8cb2c0fc0898475eb30a4ff2aa854d97:
      title: Summoning Prosperity
      parent: Prayers and Practices
    8e4e2053558f4dc2806c7768556d0f30:
      title: Mountain Smoke Offering from The Life-Force Practice of the Vidyādharas
      parent: Sang Offering
    ebd28a10485d4bb2b2b3f6ad04bcbc16:
      title: The Mountain Smoke Offering (Riwo Sangchö)
      parent: Sang Offering
    cc6fe251b77f49bbb31f38e3a9494b14:
      title: The Mountain Smoke Offering Arranged for Recitation
      parent: Sang Offering
created_at: '2022-03-01T00:35:25.499094'
last_modified_at: '2022-03-01T00:35:25.499097'
